# Generated by Django 4.1 on 2022-09-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_contact_vacancies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_person',
            new_name='number_of_person_per_room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
